title: crxxtian
description: Digital threat logs.
baseurl: ""
url: "https://crxxtian.github.io"

permalink: /blog/:title/
markdown: kramdown
future: true
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post


# Plugins if needed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
