title: Cyber Lair
description: Digital threat logs.
baseurl: ""
url: "https://yourusername.github.io"

permalink: /blog/:title/
markdown: kramdown
future: true

collections:
  posts:
    output: true
