title: Cristian's Cyber Blog
description: A digital space for cybersecurity tools, notes, and thought.
baseurl: "" # Leave as-is for GitHub Pages
url: "https://crxxtian.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Cristian
