title: Cristian's Cyber Blog
description: A digital space for cybersecurity tools, notes, and thought.
baseurl: ""
url: "https://crxxtian.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      author: Cristian
