title: Cristian's Cyber Blog
description: A digital space for cybersecurity tools, notes, and thought.
baseurl: ""
url: "https://crxxtian.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

collections:
  posts:
    output: true
    permalink: /blog/:title/
defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: post
      author: Cristian
