title: Cristian’s Cyber Lair
description: Hacking the shadows since 2025
author: Cristian
plugins:
  - jekyll-remote-theme
webrick:
  headers:
    Content-Security-Policy: "default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com;"